### ISSUE TITLE
Melhorias da segurança do banco de dados

### ISSUE THREAD

**Issue by Fullybolt** [weiner-rezcue98/web-cadastro-login-responsivo#1]
Estou propondo um projeto extra para atualização de proteções do banco de dados e conexões em sí.

**Comment by weiner-rezcue98** [comment]
> Estou propondo um projeto extra para atualização de proteções do banco de dados e conexões em sí.

Bom amigo!!! Fique a vontade, use desfrute, mais não abuse do código, rs faça como se fosse sua esposa. Sem abusar dela. Pode ser difícil, mais tenta dar uma atenção pra ela, um carinho rsrsrs

**Comment by Fullybolt** [comment]
> > Estou propondo um projeto extra para atualização de proteções do banco de dados e conexões em sí.
> 
> Bom amigo!!! Fique a vontade, use desfrute, mais não abuse do código, rs faça como se fosse sua esposa. Sem abusar dela. Pode ser difícil, mais tenta dar uma atenção pra ela, um carinho rsrsrs

kkkk Deixa pra mim

**Comment by weiner-rezcue98** [comment]
Let's go vamos lá!

**Comment by weiner-rezcue98** [comment]
> > > Estou propondo um projeto extra para atualização de proteções do banco de dados e conexões em sí.
> > 
> > 
> > Bom amigo!!! Fique a vontade, use desfrute, mais não abuse do código, rs faça como se fosse sua esposa. Sem abusar dela. Pode ser difícil, mais tenta dar uma atenção pra ela, um carinho rsrsrs
> 
> kkkk Deixa pra mim

Só boraaa

**Comment by weiner-rezcue98** [comment]
Let's gooo
